# file: design.conf

# Syntax:
# 1. The # refers comment line
# 2. Format:
# time(ms)  variable(str)   action(value of the variable)

# How it works:
# It directly changes the opt object.
# The order does not matter, since the time controls the order.
# The negative time means the command is executed **BEFORE** the session starts.

# ----------------------------------------
# Prepare
# Blink nothing
-100  selected_patches    []

# Set focus
-20 focus_r1    0.01
-20 focus_r2    0.04
-20 focus_color (0, 0, 0)

# Set layout
-1  wedges  12
-1  ring_edges  [0.125, 0.25, 0.5, 0.75, 1]
-1  grids   4

# ----------------------------------------
# Experiment
0 selected_patches   [(0, 0, 16), (1, 3, 13), (2, 11, 11), (3, 0, 9), (4, 9, 7)]
15000 selected_patches   [(0, 1, 16), (1, 0, 13), (2, 1, 11), (3, 10, 9), (4, 6, 7)]
30000 selected_patches   [(0, 4, 16), (1, 8, 13), (2, 4, 11), (3, 6, 9), (4, 10, 7)]
45000 selected_patches   [(0, 3, 16), (1, 4, 13), (2, 0, 11), (3, 4, 9), (4, 5, 7)]
60000 selected_patches   [(0, 8, 16), (1, 11, 13), (2, 8, 11), (3, 5, 9), (4, 2, 7)]
75000 selected_patches   [(0, 11, 16), (1, 9, 13), (2, 2, 11), (3, 3, 9), (4, 1, 7)]
90000 selected_patches   [(0, 2, 16), (1, 1, 13), (2, 9, 11), (3, 7, 9), (4, 8, 7)]
105000 selected_patches   [(0, 10, 16), (1, 6, 13), (2, 7, 11), (3, 1, 9), (4, 4, 7)]
120000 selected_patches   [(0, 7, 16), (1, 2, 13), (2, 5, 11), (3, 8, 9), (4, 11, 7)]
135000 selected_patches   [(0, 5, 16), (1, 10, 13), (2, 3, 11), (3, 2, 9), (4, 0, 7)]
150000 selected_patches   [(0, 9, 16), (1, 5, 13), (2, 6, 11), (3, 9, 9), (4, 7, 7)]
165000 selected_patches   [(0, 6, 16), (1, 7, 13), (2, 10, 11), (3, 11, 9), (4, 3, 7)]
180000 selected_patches   []

# ----------------------------------------
# Focus
1345    focus_color (1, 0, 0)
1595    focus_color (0, 0, 0)

17433    focus_color (1, 0, 0)
17683    focus_color (0, 0, 0)

19693    focus_color (1, 0, 0)
19943    focus_color (0, 0, 0)

24327    focus_color (1, 0, 0)
24577    focus_color (0, 0, 0)

25361    focus_color (1, 0, 0)
25611    focus_color (0, 0, 0)

26320    focus_color (1, 0, 0)
26570    focus_color (0, 0, 0)

29424    focus_color (1, 0, 0)
29674    focus_color (0, 0, 0)

30165    focus_color (1, 0, 0)
30415    focus_color (0, 0, 0)

34151    focus_color (1, 0, 0)
34401    focus_color (0, 0, 0)

36007    focus_color (1, 0, 0)
36257    focus_color (0, 0, 0)

38344    focus_color (1, 0, 0)
38594    focus_color (0, 0, 0)

41255    focus_color (1, 0, 0)
41505    focus_color (0, 0, 0)

52313    focus_color (1, 0, 0)
53563    focus_color (0, 0, 0)

69478    focus_color (1, 0, 0)
69728    focus_color (0, 0, 0)

73871    focus_color (1, 0, 0)
74121    focus_color (0, 0, 0)

78577    focus_color (1, 0, 0)
78827    focus_color (0, 0, 0)

87672    focus_color (1, 0, 0)
87922    focus_color (0, 0, 0)

89766    focus_color (1, 0, 0)
90016    focus_color (0, 0, 0)

101505    focus_color (1, 0, 0)
101755    focus_color (0, 0, 0)

106835    focus_color (1, 0, 0)
107085    focus_color (0, 0, 0)

112059    focus_color (1, 0, 0)
112309    focus_color (0, 0, 0)

119890    focus_color (1, 0, 0)
120140    focus_color (0, 0, 0)

124503    focus_color (1, 0, 0)
124753    focus_color (0, 0, 0)

133766    focus_color (1, 0, 0)
134016    focus_color (0, 0, 0)

138472    focus_color (1, 0, 0)
138722    focus_color (0, 0, 0)

147621    focus_color (1, 0, 0)
147871    focus_color (0, 0, 0)

150218    focus_color (1, 0, 0)
150468    focus_color (0, 0, 0)

159384    focus_color (1, 0, 0)
159634    focus_color (0, 0, 0)

162947    focus_color (1, 0, 0)
163197    focus_color (0, 0, 0)

172347    focus_color (1, 0, 0)
172597    focus_color (0, 0, 0)